<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="EClass">
    <eOperations name="anOperation">
      <eParameters name="eParameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore" references="http://www.eclipse.org/emf/2002/Ecore#//EDouble/%http:%2F%2F%2Forg%2Feclipse%2Femf%2Fecore%2Futil%2FExtendedMetaData%"/>
      </eParameters>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
