<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecore" nsURI="http://www.eclipse.org/emf/2002/Ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="aClass">
    <eOperations name="anOperation">
      <eAnnotations source="http://www.obeo.fr/EMFJson" references="#//aClass/anOperation ../../../nodes.ecore#//Node">
        <details key="constraints" value="WellFormedURI&#xD;&#xA;BadFormedURI"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="anOtherOperation">
      <eAnnotations source="http://www.obeo.fr/EMFJson" references="#//aClass/anOperation #//aClass"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
