= Eclipse Sirius EMF JSON

This project is part of https://eclipse.dev/sirius[Eclipse Sirius].
It provides a JSON-based implementation of EMF resources which can be used as a drop-in replacement for the default XMI-based format.

Although it is part of Sirius, this new EMF resource type can actually be used by any EMF-based application as it does not depend on the rest of the Sirius platform (neither Sirius Desktop nor Sirius Web).

== Building

The build uses https://maven.apache.org/[Apache Maven] (version 3.9.8). To launch a complete build, issue:

[source,sh]
----
mvn -f org.eclipse.sirius.emfjson/pom.xml clean package
----

from the top-level directory.

WARNING: Note that you will need to use **Java 17** or later to run the build.

== Usage

To use EMF JSON resources, simply register the `org.eclipse.sirius.emfjson.resource.JsonResourceFactoryImpl` resource factory in your resource set or in the global resource factory registry.
For example:

[source,java]
----
Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("json", new JsonResourceFactoryImpl());
----

See https://github.com/eclipse-sirius/sirius-web/tree/master/packages/emf/backend/sirius-components-emf[the Sirius Web sources] for concrete usage examples.


== License

Eclipse Public License - v 2.0
