<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="ecore"
    nsURI="http://www.eclipse.org/emf/2002/Ecore"
    nsPrefix="ecore">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="EClass">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="aReference"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="OtherEClass">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="otherReference"
        eType="#//myPackage/ThirdEClass"/>
  </eClassifiers>
  <eSubpackages
      name="myPackage"
      nsURI="http://www.obeo.fr/emfjson/json"
      nsPrefix="package">
    <eClassifiers
        xsi:type="ecore:EClass"
        name="ThirdEClass">
      <eStructuralFeatures
          xsi:type="ecore:EReference"
          name="thirdReference"
          eType="#//OtherEClass"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
