# This workflow will deploy Sirius EMF JSON to the sonatype
# staging environment. This will NOT automatically publish the artifacts. An
# authorized user must still manually close the staging repository first.

name: Generate and Deploy to Sonatype

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java SDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MYGPGKEY_SEC }}

      - name: Publish to Apache Maven Central
        run: ./mvnw -P MavenCentral deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
